import Foundation
import SwiftUI

enum AppLanguage: String, CaseIterable, Identifiable {
    case italian = "it"
    case english = "en"
    case spanish = "es"
    case french = "fr"
    case chinese = "zh-Hans"
    case arabic = "ar"
    case danish = "da"
    case norwegian = "nb"
    case swedish = "sv"

    var id: String { rawValue }

    var locale: Locale {
        Locale(identifier: rawValue)
    }

    var displayName: String {
        switch self {
        case .italian: return "Italiano"
        case .english: return "English"
        case .spanish: return "Español"
        case .french: return "Français"
        case .chinese: return "中文"
        case .arabic: return "العربية"
        case .danish: return "Dansk"
        case .norwegian: return "Norsk"
        case .swedish: return "Svenska"
        }
    }

    var aiLanguageName: String {
        switch self {
        case .italian: return "Italian"
        case .english: return "English"
        case .spanish: return "Spanish"
        case .french: return "French"
        case .chinese: return "Simplified Chinese"
        case .arabic: return "Arabic"
        case .danish: return "Danish"
        case .norwegian: return "Norwegian"
        case .swedish: return "Swedish"
        }
    }

    var weekdaySymbolsMondayFirst: [String] {
        switch self {
        case .italian: return ["Lu", "Ma", "Me", "Gi", "Ve", "Sa", "Do"]
        case .english: return ["Mo", "Tu", "We", "Th", "Fr", "Sa", "Su"]
        case .spanish: return ["Lu", "Ma", "Mi", "Ju", "Vi", "Sa", "Do"]
        case .french: return ["Lu", "Ma", "Me", "Je", "Ve", "Sa", "Di"]
        case .chinese: return ["周一", "周二", "周三", "周四", "周五", "周六", "周日"]
        case .arabic: return ["اث", "ثل", "أر", "خم", "جم", "سب", "أح"]
        case .danish: return ["ma", "ti", "on", "to", "fr", "lø", "sø"]
        case .norwegian: return ["ma", "ti", "on", "to", "fr", "lø", "sø"]
        case .swedish: return ["må", "ti", "on", "to", "fr", "lö", "sö"]
        }
    }

    static func bestMatch(for localeIdentifier: String) -> AppLanguage {
        let lowered = localeIdentifier.lowercased()

        if lowered.hasPrefix("it") { return .italian }
        if lowered.hasPrefix("en") { return .english }
        if lowered.hasPrefix("es") { return .spanish }
        if lowered.hasPrefix("fr") { return .french }
        if lowered.hasPrefix("zh") { return .chinese }
        if lowered.hasPrefix("ar") { return .arabic }
        if lowered.hasPrefix("da") { return .danish }
        if lowered.hasPrefix("nb") || lowered.hasPrefix("nn") || lowered.hasPrefix("no") { return .norwegian }
        if lowered.hasPrefix("sv") { return .swedish }

        return .italian
    }
}

enum AppLanguagePreferences {
    static let storageKey = "mindmesh.app.language"

    static var currentLanguage: AppLanguage {
        get {
            if let rawValue = UserDefaults.standard.string(forKey: storageKey),
               let language = AppLanguage(rawValue: rawValue) {
                return language
            }

            let preferredLocale = Locale.preferredLanguages.first ?? Locale.current.identifier
            return AppLanguage.bestMatch(for: preferredLocale)
        }
        set {
            UserDefaults.standard.set(newValue.rawValue, forKey: storageKey)
        }
    }
}

@MainActor
final class AppLanguageStore: ObservableObject {
    @Published var selectedLanguage: AppLanguage {
        didSet {
            AppLanguagePreferences.currentLanguage = selectedLanguage
        }
    }

    init(initialLanguage: AppLanguage = AppLanguagePreferences.currentLanguage) {
        self.selectedLanguage = initialLanguage
    }
}

struct AppStrings {
    let language: AppLanguage

    static var current: AppStrings {
        AppStrings(language: AppLanguagePreferences.currentLanguage)
    }

    func text(
        it: String,
        en: String,
        es: String,
        fr: String,
        zh: String,
        ar: String,
        da: String,
        nb: String,
        sv: String
    ) -> String {
        switch language {
        case .italian: return it
        case .english: return en
        case .spanish: return es
        case .french: return fr
        case .chinese: return zh
        case .arabic: return ar
        case .danish: return da
        case .norwegian: return nb
        case .swedish: return sv
        }
    }

    var tabHome: String { text(it: "Home", en: "Home", es: "Inicio", fr: "Accueil", zh: "首页", ar: "الرئيسية", da: "Hjem", nb: "Hjem", sv: "Hem") }
    var tabMood: String { text(it: "Umore", en: "Mood", es: "Ánimo", fr: "Humeur", zh: "心情", ar: "المزاج", da: "Humør", nb: "Humør", sv: "Humör") }
    var tabInsights: String { text(it: "Riflessioni", en: "Insights", es: "Reflexiones", fr: "Réflexions", zh: "洞察", ar: "الرؤى", da: "Refleksioner", nb: "Refleksjoner", sv: "Reflektioner") }
    var tabSettings: String { text(it: "Impostazioni", en: "Settings", es: "Ajustes", fr: "Réglages", zh: "设置", ar: "الإعدادات", da: "Indstillinger", nb: "Innstillinger", sv: "Inställningar") }

    var onboardingWelcomeTitle: String { text(it: "Benvenuto/a in Peace.", en: "Welcome to Peace.", es: "Bienvenido/a a Peace.", fr: "Bienvenue dans Peace.", zh: "欢迎来到 Peace。", ar: "مرحباً بك في Peace.", da: "Velkommen til Peace.", nb: "Velkommen til Peace.", sv: "Välkommen till Peace.") }
    var onboardingWelcomeBody: String { text(it: "Un posto semplice per capire come stai, con calma. Prima di iniziare, dimmi solo come vuoi essere chiamato/a.", en: "A simple place to understand how you feel, calmly. Before we begin, just tell me what you'd like to be called.", es: "Un lugar sencillo para entender cómo estás, con calma. Antes de empezar, solo dime cómo quieres que te llame.", fr: "Un endroit simple pour comprendre comment tu te sens, avec calme. Avant de commencer, dis-moi simplement comment tu veux être appelé(e).", zh: "这是一个帮助你平静理解自己状态的简单空间。开始之前，只要告诉我你希望我怎么称呼你。", ar: "مساحة بسيطة لتفهم كيف تشعر بهدوء. قبل أن نبدأ، فقط أخبرني كيف تحب أن أناديك.", da: "Et enkelt sted, hvor du roligt kan forstå, hvordan du har det. Før vi går i gang, så fortæl mig bare, hvad du vil kaldes.", nb: "Et enkelt sted for å forstå hvordan du har det, i ro og mak. Før vi begynner, fortell meg bare hva du vil bli kalt.", sv: "En enkel plats för att förstå hur du mår, i lugn och ro. Innan vi börjar, berätta bara vad du vill bli kallad.") }
    var onboardingFeatureSummaryTitle: String { text(it: "Sintesi chiare", en: "Clear summaries", es: "Resumen claro", fr: "Synthèses claires", zh: "清晰总结", ar: "ملخصات واضحة", da: "Klare overblik", nb: "Klare oppsummeringer", sv: "Tydliga sammanfattningar") }
    var onboardingFeatureSummaryBody: String { text(it: "Trovi subito il punto della giornata senza schermate inutili.", en: "You immediately see the point of the day without unnecessary screens.", es: "Encuentras enseguida el punto del día sin pantallas inútiles.", fr: "Tu vois tout de suite l'essentiel de la journée sans écrans inutiles.", zh: "不用多余页面，也能立刻看到当天的重点。", ar: "ترى فوراً خلاصة يومك من دون شاشات غير ضرورية.", da: "Du ser hurtigt dagens vigtigste pointe uden unødige skærme.", nb: "Du ser raskt hovedpoenget i dagen uten unødvendige skjermer.", sv: "Du ser snabbt dagens kärna utan onödiga skärmar.") }
    var onboardingFeatureMoodTitle: String { text(it: "Umore leggibile", en: "Readable mood", es: "Estado de ánimo legible", fr: "Humeur lisible", zh: "心情更清晰", ar: "مزاج واضح", da: "Let humørblik", nb: "Lesbart humør", sv: "Läsligt humör") }
    var onboardingFeatureMoodBody: String { text(it: "Tieni traccia di come stai con un gesto semplice.", en: "Track how you feel with a simple gesture.", es: "Sigue cómo te sientes con un gesto sencillo.", fr: "Suis ton état avec un geste simple.", zh: "用一个简单动作记录你的感受。", ar: "تابع كيف تشعر بإجراء بسيط.", da: "Hold styr på, hvordan du har det, med en enkel handling.", nb: "Følg med på hvordan du har det med en enkel handling.", sv: "Följ hur du mår med en enkel handling.") }
    var onboardingFeatureInsightsTitle: String { text(it: "Riflessioni utili", en: "Useful reflections", es: "Reflexiones útiles", fr: "Réflexions utiles", zh: "有用的反思", ar: "تأملات مفيدة", da: "Nyttige refleksioner", nb: "Nyttige refleksjoner", sv: "Användbara reflektioner") }
    var onboardingFeatureInsightsBody: String { text(it: "Ricevi spunti corti, concreti e facili da usare.", en: "Get short, practical insights that are easy to use.", es: "Recibe ideas breves, concretas y fáciles de usar.", fr: "Reçois des pistes courtes, concrètes et faciles à utiliser.", zh: "获得简短、具体且容易使用的启发。", ar: "احصل على أفكار قصيرة وعملية وسهلة الاستخدام.", da: "Få korte, konkrete og brugbare indsigter.", nb: "Få korte, konkrete og nyttige refleksjoner.", sv: "Få korta, konkreta och användbara insikter.") }
    var onboardingYourName: String { text(it: "Il tuo nome", en: "Your name", es: "Tu nombre", fr: "Ton nom", zh: "你的名字", ar: "اسمك", da: "Dit navn", nb: "Navnet ditt", sv: "Ditt namn") }
    var onboardingNamePlaceholder: String { text(it: "Come ti chiami?", en: "What's your name?", es: "¿Cómo te llamas?", fr: "Comment tu t'appelles ?", zh: "你叫什么名字？", ar: "ما اسمك؟", da: "Hvad hedder du?", nb: "Hva heter du?", sv: "Vad heter du?") }
    var continueButton: String { text(it: "Continua", en: "Continue", es: "Continuar", fr: "Continuer", zh: "继续", ar: "متابعة", da: "Fortsæt", nb: "Fortsett", sv: "Fortsätt") }

    var settingsTitle: String { text(it: "Impostazioni", en: "Settings", es: "Ajustes", fr: "Réglages", zh: "设置", ar: "الإعدادات", da: "Indstillinger", nb: "Innstillinger", sv: "Inställningar") }
    var settingsAppSection: String { text(it: "App", en: "App", es: "App", fr: "App", zh: "应用", ar: "التطبيق", da: "App", nb: "App", sv: "App") }
    var settingsLanguageSection: String { text(it: "Lingua", en: "Language", es: "Idioma", fr: "Langue", zh: "语言", ar: "اللغة", da: "Sprog", nb: "Språk", sv: "Språk") }
    var settingsLegalSection: String { text(it: "Legale", en: "Legal", es: "Legal", fr: "Légal", zh: "法律", ar: "قانوني", da: "Juridisk", nb: "Juridisk", sv: "Juridik") }
    var settingsAppLanguage: String { text(it: "Lingua dell'app", en: "App language", es: "Idioma de la app", fr: "Langue de l'app", zh: "应用语言", ar: "لغة التطبيق", da: "App-sprog", nb: "Appspråk", sv: "Appspråk") }
    var settingsLanguageFootnote: String { text(it: "Cambia schermate, chat e testi generati dall'AI.", en: "Changes screens, chat, and AI-generated text.", es: "Cambia pantallas, chat y textos generados por IA.", fr: "Change les écrans, le chat et les textes générés par l'IA.", zh: "会同时改变界面、聊天和 AI 生成的文本。", ar: "يغيّر الشاشات والدردشة والنصوص التي ينشئها الذكاء الاصطناعي.", da: "Ændrer skærme, chat og AI-genereret tekst.", nb: "Endrer skjermer, chat og AI-generert tekst.", sv: "Ändrar skärmar, chatten och AI-genererad text.") }
    var darkTheme: String { text(it: "Tema scuro", en: "Dark mode", es: "Tema oscuro", fr: "Mode sombre", zh: "深色模式", ar: "الوضع الداكن", da: "Mørkt tema", nb: "Mørk modus", sv: "Mörkt läge") }
    var dailyReminder: String { text(it: "Promemoria giornaliero", en: "Daily reminder", es: "Recordatorio diario", fr: "Rappel quotidien", zh: "每日提醒", ar: "تذكير يومي", da: "Daglig påmindelse", nb: "Daglig påminnelse", sv: "Daglig påminnelse") }
    var reminderTime: String { text(it: "Orario", en: "Time", es: "Hora", fr: "Horaire", zh: "时间", ar: "الوقت", da: "Tid", nb: "Tid", sv: "Tid") }
    var managePremium: String { text(it: "Gestisci Peace Premium", en: "Manage Peace Premium", es: "Gestionar Peace Premium", fr: "Gérer Peace Premium", zh: "管理 Peace Premium", ar: "إدارة Peace Premium", da: "Administrer Peace Premium", nb: "Administrer Peace Premium", sv: "Hantera Peace Premium") }
    var premiumTitle: String { text(it: "Peace Premium", en: "Peace Premium", es: "Peace Premium", fr: "Peace Premium", zh: "Peace Premium", ar: "Peace Premium", da: "Peace Premium", nb: "Peace Premium", sv: "Peace Premium") }
    var infoSection: String { text(it: "Info", en: "Info", es: "Info", fr: "Infos", zh: "信息", ar: "معلومات", da: "Info", nb: "Info", sv: "Info") }
    var versionLabel: String { text(it: "Versione", en: "Version", es: "Versión", fr: "Version", zh: "版本", ar: "الإصدار", da: "Version", nb: "Versjon", sv: "Version") }
    var privacyPolicyTitle: String { text(it: "Privacy Policy", en: "Privacy Policy", es: "Política de privacidad", fr: "Politique de confidentialité", zh: "隐私政策", ar: "سياسة الخصوصية", da: "Privatlivspolitik", nb: "Personvernerklæring", sv: "Integritetspolicy") }
    var privacyPolicyMissing: String { text(it: "Non riesco a trovare il documento privacy dentro l'app.", en: "I can't find the privacy policy document inside the app.", es: "No puedo encontrar el documento de privacidad dentro de la app.", fr: "Je ne trouve pas le document de confidentialité dans l'app.", zh: "在应用内找不到隐私政策文档。", ar: "لا يمكنني العثور على مستند سياسة الخصوصية داخل التطبيق.", da: "Jeg kan ikke finde privatlivsdokumentet i appen.", nb: "Jeg finner ikke personverndokumentet i appen.", sv: "Jag hittar inte integritetspolicyn i appen.") }
    var signOut: String { text(it: "Esci dal profilo", en: "Sign out", es: "Salir del perfil", fr: "Quitter le profil", zh: "退出个人资料", ar: "تسجيل الخروج من الملف الشخصي", da: "Log ud", nb: "Logg ut", sv: "Logga ut") }
    var openProfile: String { text(it: "Apri profilo", en: "Open profile", es: "Abrir perfil", fr: "Ouvrir le profil", zh: "打开个人资料", ar: "فتح الملف الشخصي", da: "Åbn profil", nb: "Åpne profil", sv: "Öppna profil") }
    var profileTitle: String { text(it: "Profilo", en: "Profile", es: "Perfil", fr: "Profil", zh: "个人资料", ar: "الملف الشخصي", da: "Profil", nb: "Profil", sv: "Profil") }
    var close: String { text(it: "Chiudi", en: "Close", es: "Cerrar", fr: "Fermer", zh: "关闭", ar: "إغلاق", da: "Luk", nb: "Lukk", sv: "Stäng") }
    var you: String { text(it: "Tu", en: "You", es: "Tú", fr: "Toi", zh: "你", ar: "أنت", da: "Dig", nb: "Du", sv: "Du") }
    var basicPlan: String { text(it: "Piano base", en: "Basic plan", es: "Plan básico", fr: "Forfait de base", zh: "基础版", ar: "الخطة الأساسية", da: "Basisplan", nb: "Grunnplan", sv: "Basplan") }
    var savedCheckins: String { text(it: "Check-in salvati", en: "Saved check-ins", es: "Check-ins guardados", fr: "Check-ins enregistrés", zh: "已保存打卡", ar: "عمليات تسجيل محفوظة", da: "Gemte check-ins", nb: "Lagrede innsjekker", sv: "Sparade check-ins") }
    var checkinsLast7Days: String { text(it: "Check-in ultimi 7 giorni", en: "Check-ins in the last 7 days", es: "Check-ins de los últimos 7 días", fr: "Check-ins des 7 derniers jours", zh: "最近 7 天打卡", ar: "عمليات التسجيل خلال آخر 7 أيام", da: "Check-ins de sidste 7 dage", nb: "Innsjekker de siste 7 dagene", sv: "Check-ins de senaste 7 dagarna") }
    var premiumActive: String { text(it: "Premium attivo", en: "Premium active", es: "Premium activo", fr: "Premium actif", zh: "Premium 已激活", ar: "Premium مفعّل", da: "Premium aktiv", nb: "Premium aktiv", sv: "Premium aktivt") }
    var discoverPremium: String { text(it: "Scopri Premium", en: "Discover Premium", es: "Descubre Premium", fr: "Découvrir Premium", zh: "了解 Premium", ar: "اكتشف Premium", da: "Se Premium", nb: "Oppdag Premium", sv: "Upptäck Premium") }
    var profileSummary: String { text(it: "Qui trovi il tuo spazio personale, con un riepilogo semplice di quello che stai usando davvero.", en: "Here you can find your personal space, with a simple summary of what you're actually using.", es: "Aquí encuentras tu espacio personal, con un resumen simple de lo que realmente estás usando.", fr: "Ici, tu trouves ton espace personnel, avec un résumé simple de ce que tu utilises vraiment.", zh: "这里是你的个人空间，会用简单的方式总结你真正正在使用的内容。", ar: "هنا تجد مساحتك الشخصية مع ملخص بسيط لما تستخدمه فعلاً.", da: "Her finder du dit personlige rum med en enkel oversigt over det, du faktisk bruger.", nb: "Her finner du ditt personlige rom, med en enkel oversikt over det du faktisk bruker.", sv: "Här hittar du ditt personliga utrymme med en enkel översikt över det du faktiskt använder.") }
    var premiumHeroSubtitle: String { text(it: "Per chi vuole più continuità e più profondità, senza complicare il resto.", en: "For those who want more continuity and more depth, without complicating everything else.", es: "Para quien quiere más continuidad y más profundidad, sin complicar lo demás.", fr: "Pour celles et ceux qui veulent plus de continuité et plus de profondeur, sans compliquer le reste.", zh: "适合想要更多连续性和更深层洞察，同时不想让其他部分变复杂的人。", ar: "لمن يريد مزيداً من الاستمرارية والعمق من دون تعقيد الباقي.", da: "Til dem, der vil have mere kontinuitet og mere dybde uden at gøre resten mere kompliceret.", nb: "For deg som vil ha mer kontinuitet og mer dybde uten å komplisere resten.", sv: "För dig som vill ha mer kontinuitet och mer djup utan att göra resten krångligare.") }
    var premiumFeatureInsightsTitle: String { text(it: "Riflessioni più profonde", en: "Deeper insights", es: "Reflexiones más profundas", fr: "Réflexions plus profondes", zh: "更深入的洞察", ar: "رؤى أعمق", da: "Dybere indsigter", nb: "Dypere refleksjoner", sv: "Djupare insikter") }
    var premiumFeatureInsightsBody: String { text(it: "Spunti meno generici e più mirati.", en: "Less generic and more targeted insights.", es: "Ideas menos genéricas y más enfocadas.", fr: "Des pistes moins génériques et plus ciblées.", zh: "更具体、更有针对性的启发。", ar: "أفكار أقل عمومية وأكثر دقة.", da: "Mindre generiske og mere målrettede indsigter.", nb: "Mindre generiske og mer målrettede refleksjoner.", sv: "Mindre generiska och mer träffsäkra insikter.") }
    var premiumFeatureChatTitle: String { text(it: "Chat emotiva guidata", en: "Guided emotional chat", es: "Chat emocional guiado", fr: "Chat émotionnel guidé", zh: "引导式情绪聊天", ar: "دردشة عاطفية موجهة", da: "Guidet følelseschat", nb: "Veiledet emosjonell chat", sv: "Guidad känslochat") }
    var premiumFeatureChatBody: String { text(it: "Uno spazio premium per elaborare i momenti piu difficili.", en: "A premium space to process the hardest moments.", es: "Un espacio premium para procesar los momentos más difíciles.", fr: "Un espace premium pour traverser les moments les plus difficiles.", zh: "一个帮助你梳理艰难时刻的高级空间。", ar: "مساحة مميزة للتعامل مع أصعب اللحظات.", da: "Et premium-rum til at bearbejde de sværeste øjeblikke.", nb: "Et premium-rom for å bearbeide de vanskeligste øyeblikkene.", sv: "Ett premiumutrymme för att bearbeta de svåraste stunderna.") }
    var premiumFeatureHistoryTitle: String { text(it: "Cronologia chat recenti", en: "Recent chat history", es: "Historial de chats recientes", fr: "Historique des chats récents", zh: "最近聊天记录", ar: "سجل الدردشات الأخيرة", da: "Seneste chathistorik", nb: "Nylig chathistorikk", sv: "Senaste chatthistorik") }
    var premiumFeatureHistoryBody: String { text(it: "Riprendi le conversazioni premium senza perderne il filo.", en: "Resume premium conversations without losing the thread.", es: "Retoma conversaciones premium sin perder el hilo.", fr: "Reprends les conversations premium sans en perdre le fil.", zh: "继续最近的 Premium 对话，不丢失上下文。", ar: "استأنف محادثات Premium من دون أن تفقد السياق.", da: "Genoptag premium-samtaler uden at miste tråden.", nb: "Fortsett premium-samtaler uten å miste tråden.", sv: "Återuppta premiumsamtal utan att tappa tråden.") }
    var premiumFeatureSyncTitle: String { text(it: "Sync tra dispositivi", en: "Sync across devices", es: "Sincronización entre dispositivos", fr: "Sync entre appareils", zh: "设备间同步", ar: "مزامنة بين الأجهزة", da: "Synk mellem enheder", nb: "Synk mellom enheter", sv: "Synk mellan enheter") }
    var premiumFeatureSyncBody: String { text(it: "Apri il tuo spazio ovunque, senza ricominciare.", en: "Open your space anywhere, without starting over.", es: "Abre tu espacio en cualquier lugar, sin empezar de nuevo.", fr: "Retrouve ton espace partout, sans recommencer.", zh: "在任何设备上打开你的空间，无需重新开始。", ar: "افتح مساحتك في أي مكان من دون أن تبدأ من جديد.", da: "Åbn dit rum hvor som helst uden at starte forfra.", nb: "Åpne rommet ditt hvor som helst, uten å begynne på nytt.", sv: "Öppna ditt utrymme var som helst utan att börja om.") }
    var restorePurchases: String { text(it: "Ripristina acquisti", en: "Restore purchases", es: "Restaurar compras", fr: "Restaurer les achats", zh: "恢复购买", ar: "استعادة المشتريات", da: "Gendan køb", nb: "Gjenopprett kjøp", sv: "Återställ köp") }

    var homeTitle: String { tabHome }
    var homeSubtitle: String { text(it: "Qui trovi il punto della giornata e l'andamento recente, senza altro rumore.", en: "Here you'll find the point of the day and the recent trend, without extra noise.", es: "Aquí encuentras el punto del día y la tendencia reciente, sin ruido extra.", fr: "Ici, tu trouves l'essentiel de la journée et la tendance récente, sans bruit en plus.", zh: "这里有你今天的重点和最近的变化趋势，没有多余干扰。", ar: "هنا تجد خلاصة يومك واتجاهه الأخير من دون ضجيج إضافي.", da: "Her finder du dagens hovedpunkt og den seneste udvikling uden ekstra støj.", nb: "Her finner du hovedpoenget i dagen og den siste utviklingen, uten ekstra støy.", sv: "Här hittar du dagens kärna och den senaste utvecklingen utan extra brus.") }
    var summarySection: String { text(it: "Sintesi", en: "Summary", es: "Resumen", fr: "Synthèse", zh: "总结", ar: "الملخص", da: "Overblik", nb: "Oppsummering", sv: "Sammanfattning") }
    var trendSection: String { text(it: "Andamento", en: "Trend", es: "Tendencia", fr: "Tendance", zh: "趋势", ar: "الاتجاه", da: "Udvikling", nb: "Utvikling", sv: "Utveckling") }
    var lastSevenDays: String { text(it: "Ultimi sette giorni", en: "Last seven days", es: "Últimos siete días", fr: "Sept derniers jours", zh: "最近七天", ar: "آخر سبعة أيام", da: "Seneste syv dage", nb: "Siste sju dager", sv: "Senaste sju dagarna") }
    var notePill: String { text(it: "Nota", en: "Note", es: "Nota", fr: "Note", zh: "笔记", ar: "ملاحظة", da: "Note", nb: "Notat", sv: "Notis") }
    func yourNote(day: String) -> String {
        text(it: "\(day) · La tua nota", en: "\(day) · Your note", es: "\(day) · Tu nota", fr: "\(day) · Ta note", zh: "\(day) · 你的笔记", ar: "\(day) · ملاحظتك", da: "\(day) · Din note", nb: "\(day) · Notatet ditt", sv: "\(day) · Din notis")
    }

    var moodTitle: String { tabMood }
    var moodSelectorHint: String { text(it: "Scegli la voce che ti somiglia di piu adesso.", en: "Choose the mood that feels most like you right now.", es: "Elige la emoción que más se parece a cómo te sientes ahora.", fr: "Choisis l'état qui te ressemble le plus en ce moment.", zh: "选择此刻最贴近你感受的状态。", ar: "اختر الحالة التي تشبه شعورك الآن أكثر.", da: "Vælg den stemning, der passer bedst til dig lige nu.", nb: "Velg stemningen som ligner mest på hvordan du har det nå.", sv: "Välj den känsla som passar bäst in på hur du mår just nu.") }
    var noteSection: String { notePill }
    var notePlaceholder: String { text(it: "Se vuoi, aggiungi una riga su com'e andata.", en: "If you want, add a line about how it went.", es: "Si quieres, añade una línea sobre cómo fue.", fr: "Si tu veux, ajoute une ligne sur comment ça s'est passé.", zh: "如果你愿意，可以写一句今天过得怎么样。", ar: "إذا أردت، أضف سطراً عن كيف سار يومك.", da: "Hvis du vil, kan du tilføje en linje om, hvordan det gik.", nb: "Hvis du vil, kan du legge til en linje om hvordan det gikk.", sv: "Om du vill kan du lägga till en rad om hur det gick.") }
    var updateDay: String { text(it: "Aggiorna la giornata", en: "Update today", es: "Actualizar el día", fr: "Mettre à jour la journée", zh: "更新今天", ar: "تحديث اليوم", da: "Opdatér dagen", nb: "Oppdater dagen", sv: "Uppdatera dagen") }
    var saveHowYouFeel: String { text(it: "Salva come stai", en: "Save how you feel", es: "Guardar cómo estás", fr: "Enregistrer ton état", zh: "保存你的状态", ar: "احفظ شعورك", da: "Gem hvordan du har det", nb: "Lagre hvordan du har det", sv: "Spara hur du mår") }
    var doneReady: String { text(it: "Fatto! Tutto pronto.", en: "Done! Everything is ready.", es: "Hecho. Todo listo.", fr: "C'est fait. Tout est prêt.", zh: "完成，一切就绪。", ar: "تم. كل شيء جاهز.", da: "Færdig. Alt er klart.", nb: "Ferdig. Alt er klart.", sv: "Klart. Allt är redo.") }
    var energyMovement: String { text(it: "Come si muove l'energia", en: "How energy is moving", es: "Cómo se mueve la energía", fr: "Comment l'énergie évolue", zh: "能量如何变化", ar: "كيف تتحرك الطاقة", da: "Hvordan energien bevæger sig", nb: "Hvordan energien beveger seg", sv: "Hur energin rör sig") }

    var insightsTitle: String { tabInsights }
    var last7DaysSection: String { text(it: "Ultimi 7 giorni", en: "Last 7 days", es: "Últimos 7 días", fr: "7 derniers jours", zh: "最近 7 天", ar: "آخر 7 أيام", da: "Seneste 7 dage", nb: "Siste 7 dager", sv: "Senaste 7 dagarna") }
    var overviewSection: String { text(it: "Panoramica", en: "Overview", es: "Panorámica", fr: "Vue d'ensemble", zh: "概览", ar: "نظرة عامة", da: "Overblik", nb: "Oversikt", sv: "Översikt") }
    var mostRecurringMood: String { text(it: "Voce che torna di più", en: "Most recurring mood", es: "Estado más recurrente", fr: "État le plus récurrent", zh: "最常出现的状态", ar: "الحالة الأكثر تكراراً", da: "Mest tilbagevendende stemning", nb: "Mest tilbakevendende stemning", sv: "Mest återkommande känsla") }
    var recentTrend: String { text(it: "Andamento recente", en: "Recent trend", es: "Tendencia reciente", fr: "Tendance récente", zh: "近期趋势", ar: "الاتجاه الأخير", da: "Seneste udvikling", nb: "Nylig utvikling", sv: "Senaste utvecklingen") }
    var averageEnergy: String { text(it: "Energia media", en: "Average energy", es: "Energía media", fr: "Énergie moyenne", zh: "平均能量", ar: "متوسط الطاقة", da: "Gennemsnitlig energi", nb: "Gjennomsnittlig energi", sv: "Genomsnittlig energi") }
    var toneVariation: String { text(it: "Quanto cambia il tono", en: "Tone variation", es: "Cuánto cambia el tono", fr: "Variation du ton", zh: "情绪波动", ar: "مدى تغيّر النبرة", da: "Hvor meget tonen ændrer sig", nb: "Hvor mye tonen endrer seg", sv: "Hur mycket tonen varierar") }
    var fullAnalysis: String { text(it: "Analisi completa", en: "Full analysis", es: "Análisis completo", fr: "Analyse complète", zh: "完整分析", ar: "التحليل الكامل", da: "Fuld analyse", nb: "Full analyse", sv: "Full analys") }
    var premiumBadge: String { text(it: "Premium", en: "Premium", es: "Premium", fr: "Premium", zh: "Premium", ar: "Premium", da: "Premium", nb: "Premium", sv: "Premium") }
    var regenerateAnalysis: String { text(it: "Rigenera analisi", en: "Regenerate analysis", es: "Regenerar análisis", fr: "Régénérer l'analyse", zh: "重新生成分析", ar: "إعادة توليد التحليل", da: "Generér analysen igen", nb: "Generer analysen på nytt", sv: "Generera analysen igen") }
    var openPremiumChat: String { text(it: "Apri la chat Premium", en: "Open Premium chat", es: "Abrir chat Premium", fr: "Ouvrir le chat Premium", zh: "打开 Premium 聊天", ar: "افتح دردشة Premium", da: "Åbn Premium-chat", nb: "Åpne Premium-chat", sv: "Öppna Premium-chatten") }
    var lockedAnalysisTitle: String { text(it: "La panoramica è pronta. L'analisi completa si sblocca con Premium.", en: "The overview is ready. The full analysis unlocks with Premium.", es: "La panorámica está lista. El análisis completo se desbloquea con Premium.", fr: "La vue d'ensemble est prête. L'analyse complète se débloque avec Premium.", zh: "概览已准备好，完整分析可通过 Premium 解锁。", ar: "النظرة العامة جاهزة. التحليل الكامل يُفتح مع Premium.", da: "Overblikket er klar. Den fulde analyse låses op med Premium.", nb: "Oversikten er klar. Den fulle analysen låses opp med Premium.", sv: "Översikten är klar. Den fullständiga analysen låses upp med Premium.") }
    var lockedAnalysisBody: String { text(it: "Con Premium puoi ottenere una lettura dettagliatissima generata on-device dal Foundation Model, costruita davvero sulle registrazioni recenti e sulle note che hai scritto.", en: "With Premium you can get a very detailed on-device reading generated by the Foundation Model, built from your recent entries and notes.", es: "Con Premium puedes obtener una lectura muy detallada generada en el dispositivo por el Foundation Model, construida sobre tus registros recientes y tus notas.", fr: "Avec Premium, tu peux obtenir une lecture très détaillée générée sur l'appareil par le Foundation Model, construite à partir de tes entrées récentes et de tes notes.", zh: "通过 Premium，你可以获得由 Foundation Model 在设备端生成的超详细分析，真正基于你最近的记录和笔记。", ar: "مع Premium يمكنك الحصول على قراءة مفصلة جداً يتم توليدها على الجهاز بواسطة Foundation Model اعتماداً على تسجيلاتك الأخيرة وملاحظاتك.", da: "Med Premium kan du få en meget detaljeret analyse genereret på enheden af Foundation Model, bygget på dine seneste registreringer og noter.", nb: "Med Premium kan du få en svært detaljert analyse generert på enheten av Foundation Model, bygget på de siste registreringene og notatene dine.", sv: "Med Premium kan du få en mycket detaljerad analys som genereras på enheten av Foundation Model, byggd på dina senaste registreringar och anteckningar.") }
    var includedInPremium: String { text(it: "Incluso nel Premium", en: "Included in Premium", es: "Incluido en Premium", fr: "Inclus dans Premium", zh: "Premium 包含", ar: "مضمن في Premium", da: "Inkluderet i Premium", nb: "Inkludert i Premium", sv: "Ingår i Premium") }
    var premiumBundleDescription: String { text(it: "Un'analisi premium molto piu profonda dei pattern emotivi recenti, piu una chat di supporto per mettere ordine nei pensieri difficili.", en: "A much deeper premium analysis of recent emotional patterns, plus a support chat to help organize difficult thoughts.", es: "Un análisis premium mucho más profundo de los patrones emocionales recientes, más un chat de apoyo para ordenar pensamientos difíciles.", fr: "Une analyse premium bien plus profonde des schémas émotionnels récents, plus un chat de soutien pour mettre de l'ordre dans les pensées difficiles.", zh: "更深入的近期情绪模式高级分析，以及一个帮助你梳理困难想法的支持聊天。", ar: "تحليل Premium أعمق بكثير للأنماط العاطفية الأخيرة، إضافة إلى دردشة دعم لترتيب الأفكار الصعبة.", da: "En langt dybere premium-analyse af de seneste følelsesmønstre plus en støttende chat til at skabe orden i svære tanker.", nb: "En mye dypere premium-analyse av de siste emosjonelle mønstrene, pluss en støttende chat for å rydde i vanskelige tanker.", sv: "En mycket djupare premiumanalys av de senaste känslomönstren, plus en stödchatt som hjälper dig att sortera svåra tankar.") }
    var unlockFullAnalysis: String { text(it: "Sblocca l'analisi completa", en: "Unlock full analysis", es: "Desbloquear análisis completo", fr: "Débloquer l'analyse complète", zh: "解锁完整分析", ar: "افتح التحليل الكامل", da: "Lås den fulde analyse op", nb: "Lås opp full analyse", sv: "Lås upp full analys") }
    var premiumLoadingTitle: String { text(it: "Sto preparando una lettura premium molto piu profonda dei tuoi check-in recenti.", en: "I'm preparing a much deeper premium reading of your recent check-ins.", es: "Estoy preparando una lectura premium mucho más profunda de tus check-ins recientes.", fr: "Je prépare une lecture premium beaucoup plus profonde de tes check-ins récents.", zh: "我正在准备一份更深入的 Premium 分析，基于你最近的打卡。", ar: "أقوم بإعداد قراءة Premium أعمق بكثير لعمليات تسجيلك الأخيرة.", da: "Jeg forbereder en langt dybere premium-læsning af dine seneste check-ins.", nb: "Jeg forbereder en mye dypere premium-lesning av de siste innsjekkene dine.", sv: "Jag förbereder en mycket djupare premiumläsning av dina senaste check-ins.") }
    var premiumLoadingBody: String { text(it: "L'analisi usa Apple Foundation Model e tiene conto del ritmo, delle note testuali, dei cambi di tono e dei segnali da monitorare.", en: "The analysis uses Apple Foundation Model and considers rhythm, text notes, tone shifts, and signals worth monitoring.", es: "El análisis usa Apple Foundation Model y tiene en cuenta el ritmo, las notas, los cambios de tono y las señales a vigilar.", fr: "L'analyse utilise Apple Foundation Model et prend en compte le rythme, les notes, les changements de ton et les signaux à surveiller.", zh: "分析使用 Apple Foundation Model，会综合节奏、文字笔记、语气变化和需要关注的信号。", ar: "يستخدم التحليل Apple Foundation Model ويأخذ في الاعتبار الإيقاع والملاحظات النصية وتغيّر النبرة والإشارات التي يجدر متابعتها.", da: "Analysen bruger Apple Foundation Model og tager højde for rytme, tekstnoter, toneskift og signaler, der bør overvåges.", nb: "Analysen bruker Apple Foundation Model og tar hensyn til rytme, tekstnotater, toneskifter og signaler som er verdt å følge med på.", sv: "Analysen använder Apple Foundation Model och tar hänsyn till rytm, anteckningar, tonskiften och signaler att hålla koll på.") }
    func premiumGeneratedAt(_ date: String) -> String {
        text(it: "Generata il \(date) · Apple Foundation Model", en: "Generated on \(date) · Apple Foundation Model", es: "Generado el \(date) · Apple Foundation Model", fr: "Générée le \(date) · Apple Foundation Model", zh: "生成于 \(date) · Apple Foundation Model", ar: "تم الإنشاء في \(date) · Apple Foundation Model", da: "Genereret \(date) · Apple Foundation Model", nb: "Generert \(date) · Apple Foundation Model", sv: "Genererad \(date) · Apple Foundation Model")
    }
    var premiumAnalysisUnavailable: String { text(it: "Analisi premium non disponibile", en: "Premium analysis unavailable", es: "Análisis premium no disponible", fr: "Analyse premium indisponible", zh: "Premium 分析不可用", ar: "تحليل Premium غير متاح", da: "Premium-analysen er ikke tilgængelig", nb: "Premium-analysen er ikke tilgjengelig", sv: "Premiumanalysen är inte tillgänglig") }
    var notEnoughDataTitle: String { text(it: "Non ho ancora abbastanza dati per una riflessione approfondita.", en: "There isn't enough data yet for a deeper reflection.", es: "Todavía no hay suficientes datos para una reflexión más profunda.", fr: "Il n'y a pas encore assez de données pour une réflexion approfondie.", zh: "目前还没有足够的数据进行更深入的分析。", ar: "لا توجد بيانات كافية بعد لقراءة أعمق.", da: "Der er endnu ikke nok data til en dybere refleksion.", nb: "Det er ennå ikke nok data for en dypere refleksjon.", sv: "Det finns ännu inte tillräckligt med data för en djupare reflektion.") }
    var notEnoughDataBody: String { text(it: "Registra piu spesso il tuo umore nei prossimi giorni. Quando ci saranno almeno 3 registrazioni recenti, qui comparira una panoramica reale dell'andamento.", en: "Track your mood more often over the next few days. Once there are at least 3 recent entries, a real overview will appear here.", es: "Registra tu estado de ánimo con más frecuencia en los próximos días. Cuando haya al menos 3 registros recientes, aparecerá aquí una panorámica real.", fr: "Enregistre ton humeur plus souvent dans les prochains jours. Lorsqu'il y aura au moins 3 entrées récentes, un vrai aperçu apparaîtra ici.", zh: "接下来几天更频繁地记录你的心情。只要最近有至少 3 条记录，这里就会显示真实的趋势概览。", ar: "سجّل مزاجك بوتيرة أكبر خلال الأيام القادمة. عندما تكون هناك 3 تسجيلات حديثة على الأقل، ستظهر هنا نظرة حقيقية على الاتجاه.", da: "Registrér dit humør lidt oftere de næste dage. Når der er mindst 3 nylige registreringer, vises et reelt overblik her.", nb: "Registrer humøret ditt litt oftere de neste dagene. Når det finnes minst 3 nylige registreringer, vises en reell oversikt her.", sv: "Registrera ditt humör oftare de kommande dagarna. När det finns minst 3 senaste registreringar visas en riktig översikt här.") }
    var premiumAnalysisTitleFallback: String { text(it: "Analisi emotiva premium", en: "Premium emotional analysis", es: "Análisis emocional premium", fr: "Analyse émotionnelle premium", zh: "Premium 情绪分析", ar: "تحليل عاطفي Premium", da: "Premium følelsesanalyse", nb: "Premium følelsesanalyse", sv: "Premium känsloanalys") }

    var premiumChatTitle: String { text(it: "Chat Premium", en: "Premium chat", es: "Chat Premium", fr: "Chat Premium", zh: "Premium 聊天", ar: "دردشة Premium", da: "Premium-chat", nb: "Premium-chat", sv: "Premium-chatt") }
    var newChat: String { text(it: "Nuova", en: "New", es: "Nueva", fr: "Nouveau", zh: "新建", ar: "جديد", da: "Ny", nb: "Ny", sv: "Ny") }
    var supportChatSafety: String { text(it: "Supporto emotivo leggero: utile per riflettere, non per emergenze, diagnosi o terapia.", en: "Light emotional support: useful for reflection, not for emergencies, diagnosis, or therapy.", es: "Apoyo emocional ligero: útil para reflexionar, no para emergencias, diagnósticos o terapia.", fr: "Soutien émotionnel léger : utile pour réfléchir, pas pour les urgences, le diagnostic ou la thérapie.", zh: "轻度情绪支持：适合帮助你整理想法，不适用于紧急情况、诊断或治疗。", ar: "دعم عاطفي خفيف: مفيد للتأمل، وليس للطوارئ أو التشخيص أو العلاج.", da: "Let følelsesmæssig støtte: nyttigt til refleksion, ikke til nødsituationer, diagnoser eller terapi.", nb: "Lett emosjonell støtte: nyttig for refleksjon, ikke for nødssituasjoner, diagnose eller terapi.", sv: "Lätt känslomässigt stöd: bra för reflektion, inte för nödlägen, diagnoser eller terapi.") }
    var recentChats: String { text(it: "Recenti", en: "Recent", es: "Recientes", fr: "Récents", zh: "最近", ar: "الأخيرة", da: "Seneste", nb: "Nylige", sv: "Senaste") }
    var premiumOnly: String { text(it: "Solo Premium", en: "Premium only", es: "Solo Premium", fr: "Premium uniquement", zh: "仅限 Premium", ar: "Premium فقط", da: "Kun Premium", nb: "Kun Premium", sv: "Endast Premium") }
    var supportTyping: String { text(it: "Sto organizzando una risposta utile...", en: "I'm putting together a helpful reply...", es: "Estoy preparando una respuesta útil...", fr: "Je prépare une réponse utile...", zh: "我正在整理一条有帮助的回复……", ar: "أرتّب الآن رداً مفيداً...", da: "Jeg sammensætter et nyttigt svar...", nb: "Jeg setter sammen et nyttig svar...", sv: "Jag sätter ihop ett hjälpsamt svar...") }
    var supportInputPlaceholder: String { text(it: "Scrivi quello che senti...", en: "Write what you're feeling...", es: "Escribe lo que sientes...", fr: "Écris ce que tu ressens...", zh: "写下你的感受……", ar: "اكتب ما تشعر به...", da: "Skriv det, du føler...", nb: "Skriv det du føler...", sv: "Skriv vad du känner...") }
    var recentConversationFallback: String { text(it: "Conversazione recente", en: "Recent conversation", es: "Conversación reciente", fr: "Conversation récente", zh: "最近对话", ar: "محادثة حديثة", da: "Seneste samtale", nb: "Nylig samtale", sv: "Senaste samtal") }

    var aiAssisted: String { text(it: "Assistita", en: "Assisted", es: "Asistida", fr: "Assistée", zh: "AI 辅助", ar: "بمساعدة الذكاء الاصطناعي", da: "AI-hjulpet", nb: "AI-støttet", sv: "AI-stödd") }
    var howStrong: String { text(it: "Quanto pesa", en: "How strong it is", es: "Qué tan fuerte es", fr: "Son intensité", zh: "强度", ar: "مدى شدته", da: "Hvor stærkt det er", nb: "Hvor sterkt det er", sv: "Hur starkt det är") }

    var greetingMorning: String { text(it: "Buongiorno", en: "Good morning", es: "Buenos días", fr: "Bonjour", zh: "早上好", ar: "صباح الخير", da: "Godmorgen", nb: "God morgen", sv: "God morgon") }
    var greetingAfternoon: String { text(it: "Buon pomeriggio", en: "Good afternoon", es: "Buenas tardes", fr: "Bon après-midi", zh: "下午好", ar: "مساء الخير", da: "God eftermiddag", nb: "God ettermiddag", sv: "God eftermiddag") }
    var greetingEvening: String { text(it: "Buonasera", en: "Good evening", es: "Buenas noches", fr: "Bonsoir", zh: "晚上好", ar: "مساء الخير", da: "God aften", nb: "God kveld", sv: "God kväll") }
    var displayNameFallback: String { text(it: "tu", en: "you", es: "tú", fr: "toi", zh: "你", ar: "أنت", da: "dig", nb: "du", sv: "du") }
    var startWithCheckin: String { text(it: "Comincia da un check-in.", en: "Start with a check-in.", es: "Empieza con un check-in.", fr: "Commence par un check-in.", zh: "先从一次打卡开始。", ar: "ابدأ بتسجيل واحد.", da: "Start med et check-in.", nb: "Start med en innsjekk.", sv: "Börja med en check-in.") }
    var startTrackingMessage: String { text(it: "Quando inizi a registrare l'umore con continuita, qui troverai una sintesi reale della settimana.", en: "When you start logging your mood consistently, you'll find a real weekly summary here.", es: "Cuando empieces a registrar tu estado de ánimo con constancia, aquí encontrarás un resumen real de la semana.", fr: "Quand tu commenceras à enregistrer ton humeur régulièrement, tu trouveras ici un vrai résumé de la semaine.", zh: "当你开始持续记录心情时，这里会显示真实的一周总结。", ar: "عندما تبدأ بتسجيل مزاجك باستمرار، ستجد هنا ملخصاً أسبوعياً حقيقياً.", da: "Når du begynder at registrere dit humør løbende, finder du en reel opsummering af ugen her.", nb: "Når du begynner å registrere humøret ditt jevnlig, finner du en ekte ukesoppsummering her.", sv: "När du börjar registrera ditt humör regelbundet hittar du en verklig veckosammanfattning här.") }
        

    func reminderActive(at time: String) -> String {
        text(it: "Promemoria attivo ogni giorno alle \(time).", en: "Reminder active every day at \(time).", es: "Recordatorio activo todos los días a las \(time).", fr: "Rappel actif tous les jours à \(time).", zh: "提醒已开启，每天 \(time)。", ar: "التذكير مفعّل كل يوم في \(time).", da: "Påmindelse aktiv hver dag kl. \(time).", nb: "Påminnelse aktiv hver dag kl. \(time).", sv: "Påminnelse aktiv varje dag kl. \(time).")
    }
    var noReminder: String { text(it: "Nessun promemoria attivo.", en: "No active reminder.", es: "No hay ningún recordatorio activo.", fr: "Aucun rappel actif.", zh: "当前没有开启提醒。", ar: "لا يوجد تذكير مفعّل.", da: "Ingen aktiv påmindelse.", nb: "Ingen aktiv påminnelse.", sv: "Ingen aktiv påminnelse.") }
    var notificationsDisabled: String { text(it: "Le notifiche sono disattivate. Puoi riattivarle dalle impostazioni di sistema.", en: "Notifications are disabled. You can turn them back on in system settings.", es: "Las notificaciones están desactivadas. Puedes volver a activarlas desde los ajustes del sistema.", fr: "Les notifications sont désactivées. Tu peux les réactiver dans les réglages du système.", zh: "通知已关闭，你可以在系统设置中重新开启。", ar: "الإشعارات معطّلة. يمكنك تفعيلها من إعدادات النظام.", da: "Notifikationer er slået fra. Du kan aktivere dem igen i systemindstillingerne.", nb: "Varsler er slått av. Du kan aktivere dem igjen i systeminnstillingene.", sv: "Notiser är avstängda. Du kan slå på dem igen i systeminställningarna.") }
    var reminderPermissionNeeded: String { text(it: "Serve il tuo consenso per attivare il promemoria.", en: "Your permission is needed to activate the reminder.", es: "Se necesita tu permiso para activar el recordatorio.", fr: "Ton autorisation est nécessaire pour activer le rappel.", zh: "需要你的授权才能开启提醒。", ar: "نحتاج إلى موافقتك لتفعيل التذكير.", da: "Vi har brug for din tilladelse for at aktivere påmindelsen.", nb: "Vi trenger tillatelsen din for å aktivere påminnelsen.", sv: "Vi behöver ditt tillstånd för att aktivera påminnelsen.") }
    var reminderCheckSettings: String { text(it: "Controlla le impostazioni notifiche per confermare il promemoria.", en: "Check notification settings to confirm the reminder.", es: "Revisa la configuración de notificaciones para confirmar el recordatorio.", fr: "Vérifie les réglages de notification pour confirmer le rappel.", zh: "请检查通知设置以确认提醒。", ar: "تحقق من إعدادات الإشعارات لتأكيد التذكير.", da: "Tjek notifikationsindstillingerne for at bekræfte påmindelsen.", nb: "Sjekk varselinnstillingene for å bekrefte påminnelsen.", sv: "Kontrollera notisinställningarna för att bekräfta påminnelsen.") }
    var reminderNotificationBody: String { text(it: "Prenditi un momento per segnare come stai oggi.", en: "Take a moment to log how you're feeling today.", es: "Tómate un momento para registrar cómo te sientes hoy.", fr: "Prends un moment pour noter comment tu te sens aujourd'hui.", zh: "花一点时间记录一下你今天的状态。", ar: "خذ لحظة لتسجل كيف تشعر اليوم.", da: "Tag et øjeblik til at registrere, hvordan du har det i dag.", nb: "Ta et øyeblikk for å registrere hvordan du har det i dag.", sv: "Ta en stund och registrera hur du känner dig idag.") }

    func supportWelcome(snapshotTitle: String?) -> String {
        if let snapshotTitle {
            return text(
                it: "Questa chat premium ti aiuta a mettere ordine nelle emozioni difficili, senza fare diagnosi. Dal tuo andamento recente emerge questo: \(snapshotTitle.lowercased())\n\nSe vuoi, raccontami cosa pesa di piu oggi e proviamo a scomporlo insieme.",
                en: "This premium chat helps you sort through difficult emotions without making diagnoses. Your recent pattern suggests this: \(snapshotTitle.lowercased())\n\nIf you want, tell me what feels heaviest today and we can break it down together.",
                es: "Este chat premium te ayuda a ordenar emociones difíciles sin hacer diagnósticos. De tu tendencia reciente emerge esto: \(snapshotTitle.lowercased())\n\nSi quieres, cuéntame qué pesa más hoy y lo descomponemos juntos.",
                fr: "Ce chat premium t'aide à mettre de l'ordre dans les émotions difficiles, sans poser de diagnostic. Voici ce qui ressort de ta tendance récente : \(snapshotTitle.lowercased())\n\nSi tu veux, raconte-moi ce qui pèse le plus aujourd'hui et on peut le décomposer ensemble.",
                zh: "这个 Premium 聊天会帮助你梳理复杂情绪，而不会做出诊断。你最近的状态里最明显的是：\(snapshotTitle.lowercased())\n\n如果你愿意，可以告诉我今天最让你有压力的是什么，我们一起把它拆开来看。",
                ar: "تساعدك هذه الدردشة المميزة على ترتيب المشاعر الصعبة من دون تشخيص. هذا ما يظهر من اتجاهك الأخير: \(snapshotTitle.lowercased())\n\nإذا أردت، أخبرني ما الذي يثقل عليك أكثر اليوم وسنحاول تفكيكه معاً.",
                da: "Denne premium-chat hjælper dig med at skabe orden i svære følelser uden at stille diagnoser. Dit seneste mønster peger på dette: \(snapshotTitle.lowercased())\n\nHvis du vil, så fortæl mig, hvad der fylder mest i dag, så kan vi dele det op sammen.",
                nb: "Denne premium-chatten hjelper deg med å sortere vanskelige følelser uten å stille diagnoser. Dette ser ut til å komme fram i mønsteret ditt i det siste: \(snapshotTitle.lowercased())\n\nHvis du vil, kan du fortelle hva som tynger mest i dag, så kan vi dele det opp sammen.",
                sv: "Den här premiumchatten hjälper dig att sortera svåra känslor utan att ställa diagnoser. Det här framträder i ditt senaste mönster: \(snapshotTitle.lowercased())\n\nOm du vill kan du berätta vad som känns tyngst idag, så kan vi bryta ner det tillsammans."
            )
        }

        return text(
            it: "Questa chat premium ti aiuta a dare un nome alle emozioni difficili e a renderle piu leggibili, senza fare diagnosi o sostituire un professionista.\n\nScrivimi cosa senti in questo momento, anche in modo disordinato.",
            en: "This premium chat helps you name difficult emotions and make them easier to understand, without diagnosing or replacing a professional.\n\nWrite to me about what you're feeling right now, even if it comes out messy.",
            es: "Este chat premium te ayuda a poner nombre a las emociones difíciles y a hacerlas más comprensibles, sin diagnosticar ni sustituir a un profesional.\n\nEscríbeme lo que sientes ahora mismo, aunque salga desordenado.",
            fr: "Ce chat premium t'aide à nommer les émotions difficiles et à les rendre plus lisibles, sans poser de diagnostic ni remplacer un professionnel.\n\nÉcris-moi ce que tu ressens maintenant, même de façon désordonnée.",
            zh: "这个 Premium 聊天会帮助你给复杂情绪命名，并让它们更容易理解，不会做诊断，也不能替代专业人士。\n\n把你现在的感受写给我，哪怕很混乱也没关系。",
            ar: "تساعدك هذه الدردشة المميزة على تسمية المشاعر الصعبة وجعلها أوضح، من دون تشخيص أو استبدال مختص.\n\nاكتب لي ما تشعر به الآن، حتى لو كان بشكل غير مرتب.",
            da: "Denne premium-chat hjælper dig med at sætte ord på svære følelser og gøre dem lettere at forstå uden at stille diagnoser eller erstatte en professionel.\n\nSkriv til mig, hvad du føler lige nu, også selv om det er rodet.",
            nb: "Denne premium-chatten hjelper deg med å sette ord på vanskelige følelser og gjøre dem lettere å forstå, uten å stille diagnoser eller erstatte en profesjonell.\n\nSkriv til meg hva du føler akkurat nå, selv om det kommer usortert.",
            sv: "Den här premiumchatten hjälper dig att sätta ord på svåra känslor och göra dem mer begripliga, utan att ställa diagnoser eller ersätta en professionell.\n\nSkriv till mig hur du känner just nu, även om det blir rörigt."
        )
    }
    var quickPromptOverwhelmed: String { text(it: "Mi sento sopraffatta oggi", en: "I feel overwhelmed today", es: "Hoy me siento sobrepasada", fr: "Je me sens dépassé(e) aujourd'hui", zh: "我今天觉得快撑不住了", ar: "أشعر أنني مثقل/ة اليوم", da: "Jeg føler mig overvældet i dag", nb: "Jeg føler meg overveldet i dag", sv: "Jag känner mig överväldigad idag") }
    var quickPromptNegativeThoughts: String { text(it: "Ho pensieri molto negativi", en: "I'm having very negative thoughts", es: "Tengo pensamientos muy negativos", fr: "J'ai des pensées très négatives", zh: "我有很多非常消极的想法", ar: "تراودني أفكار سلبية جداً", da: "Jeg har meget negative tanker", nb: "Jeg har veldig negative tanker", sv: "Jag har väldigt negativa tankar") }
    var quickPromptGuilt: String { text(it: "Mi sento in colpa e faccio fatica a staccare", en: "I feel guilty and I can't switch off", es: "Me siento culpable y me cuesta desconectar", fr: "Je me sens coupable et j'ai du mal à décrocher", zh: "我有负罪感，而且很难停下来", ar: "أشعر بالذنب ويصعب عليّ أن أتوقف", da: "Jeg føler skyld og har svært ved at koble fra", nb: "Jeg føler skyld og klarer ikke å koble av", sv: "Jag känner skuld och har svårt att koppla av") }
    var quickPromptHelpUnderstand: String { text(it: "Aiutami a capire cosa sto provando", en: "Help me understand what I'm feeling", es: "Ayúdame a entender lo que estoy sintiendo", fr: "Aide-moi à comprendre ce que je ressens", zh: "帮我理解我现在的感受", ar: "ساعدني على فهم ما أشعر به", da: "Hjælp mig med at forstå, hvad jeg føler", nb: "Hjelp meg å forstå hva jeg føler", sv: "Hjälp mig att förstå vad jag känner") }
    var supportChatUnavailable: String { text(it: "Chat AI non disponibile", en: "AI chat unavailable", es: "Chat de IA no disponible", fr: "Chat IA indisponible", zh: "AI 聊天不可用", ar: "دردشة الذكاء الاصطناعي غير متاحة", da: "AI-chat er ikke tilgængelig", nb: "AI-chat er ikke tilgjengelig", sv: "AI-chatten är inte tillgänglig") }
    var supportFoundationUnavailable: String { text(it: "Apple Intelligence non è disponibile su questo dispositivo, quindi questa chat non può usare il Foundation Model.", en: "Apple Intelligence isn't available on this device, so this chat can't use the Foundation Model.", es: "Apple Intelligence no está disponible en este dispositivo, así que este chat no puede usar el Foundation Model.", fr: "Apple Intelligence n'est pas disponible sur cet appareil, donc ce chat ne peut pas utiliser le Foundation Model.", zh: "此设备不支持 Apple Intelligence，因此此聊天无法使用 Foundation Model。", ar: "Apple Intelligence غير متاح على هذا الجهاز، لذلك لا يمكن لهذه الدردشة استخدام Foundation Model.", da: "Apple Intelligence er ikke tilgængelig på denne enhed, så denne chat kan ikke bruge Foundation Model.", nb: "Apple Intelligence er ikke tilgjengelig på denne enheten, så denne chatten kan ikke bruke Foundation Model.", sv: "Apple Intelligence är inte tillgängligt på den här enheten, så den här chatten kan inte använda Foundation Model.") }
    var supportNotConfigured: String { text(it: "La chat AI non è ancora attiva. Inserisci una configurazione OpenAI o collega un backend per usare un modello reale.", en: "The AI chat isn't active yet. Add an OpenAI configuration or connect a backend to use a real model.", es: "El chat de IA aún no está activo. Añade una configuración de OpenAI o conecta un backend para usar un modelo real.", fr: "Le chat IA n'est pas encore actif. Ajoute une configuration OpenAI ou connecte un backend pour utiliser un vrai modèle.", zh: "AI 聊天尚未启用。请添加 OpenAI 配置或连接后端以使用真实模型。", ar: "دردشة الذكاء الاصطناعي غير مفعلة بعد. أضف إعداد OpenAI أو اربط خلفية لاستخدام نموذج حقيقي.", da: "AI-chatten er ikke aktiv endnu. Tilføj en OpenAI-konfiguration eller forbind et backend for at bruge en rigtig model.", nb: "AI-chatten er ikke aktiv ennå. Legg til OpenAI-konfigurasjon eller koble til en backend for å bruke en ekte modell.", sv: "AI-chatten är inte aktiv ännu. Lägg till en OpenAI-konfiguration eller anslut en backend för att använda en riktig modell.") }
    var supportModelNoReply: String { text(it: "In questo momento il modello AI non sta rispondendo. Riprova tra poco.", en: "The AI model isn't responding right now. Try again shortly.", es: "El modelo de IA no está respondiendo ahora mismo. Inténtalo de nuevo en un momento.", fr: "Le modèle IA ne répond pas en ce moment. Réessaie dans un instant.", zh: "AI 模型当前没有响应，请稍后重试。", ar: "نموذج الذكاء الاصطناعي لا يرد الآن. حاول مرة أخرى بعد قليل.", da: "AI-modellen svarer ikke lige nu. Prøv igen om lidt.", nb: "AI-modellen svarer ikke akkurat nå. Prøv igjen om litt.", sv: "AI-modellen svarar inte just nu. Försök igen om en stund.") }
    var missingOpenAIOrBackend: String { text(it: "Manca `MINDMESH_OPENAI_API_KEY` oppure un endpoint backend valido.", en: "Missing `MINDMESH_OPENAI_API_KEY` or a valid backend endpoint.", es: "Falta `MINDMESH_OPENAI_API_KEY` o un endpoint de backend válido.", fr: "Il manque `MINDMESH_OPENAI_API_KEY` ou un endpoint backend valide.", zh: "缺少 `MINDMESH_OPENAI_API_KEY` 或有效的后端端点。", ar: "هناك نقص في `MINDMESH_OPENAI_API_KEY` أو في نقطة خلفية صالحة.", da: "Der mangler `MINDMESH_OPENAI_API_KEY` eller et gyldigt backend-endpoint.", nb: "Mangler `MINDMESH_OPENAI_API_KEY` eller et gyldig backend-endepunkt.", sv: "Saknar `MINDMESH_OPENAI_API_KEY` eller en giltig backend-endpoint.") }
    var invalidRemoteRequest: String { text(it: "La richiesta al modello remoto e fallita oppure la configurazione non e valida.", en: "The request to the remote model failed, or the configuration is invalid.", es: "La solicitud al modelo remoto falló o la configuración no es válida.", fr: "La requête vers le modèle distant a échoué ou la configuration n'est pas valide.", zh: "远程模型请求失败，或配置无效。", ar: "فشل الطلب إلى النموذج البعيد أو أن الإعداد غير صالح.", da: "Anmodningen til den eksterne model mislykkedes, eller konfigurationen er ugyldig.", nb: "Forespørselen til den eksterne modellen mislyktes, eller konfigurasjonen er ugyldig.", sv: "Begäran till den externa modellen misslyckades eller så är konfigurationen ogiltig.") }

    var sourceLocalBackend: String { text(it: "Backend AI Locale", en: "Local AI backend", es: "Backend de IA local", fr: "Backend IA local", zh: "本地 AI 后端", ar: "خلفية ذكاء اصطناعي محلية", da: "Lokal AI-backend", nb: "Lokal AI-backend", sv: "Lokal AI-backend") }
    var sourceLocalBackendDetail: String { text(it: "Connesso a http://127.0.0.1:8787", en: "Connected to http://127.0.0.1:8787", es: "Conectado a http://127.0.0.1:8787", fr: "Connecté à http://127.0.0.1:8787", zh: "已连接到 http://127.0.0.1:8787", ar: "متصل بـ http://127.0.0.1:8787", da: "Forbundet til http://127.0.0.1:8787", nb: "Tilkoblet http://127.0.0.1:8787", sv: "Ansluten till http://127.0.0.1:8787") }
    var sourceConfiguredBackend: String { text(it: "Backend AI configurato", en: "Configured AI backend", es: "Backend de IA configurado", fr: "Backend IA configuré", zh: "已配置 AI 后端", ar: "خلفية ذكاء اصطناعي مُعدّة", da: "Konfigureret AI-backend", nb: "Konfigurert AI-backend", sv: "Konfigurerad AI-backend") }
    var sourceConfiguredBackendDetail: String { text(it: "La chat usa il backend AI remoto configurato.", en: "The chat uses the configured remote AI backend.", es: "El chat usa el backend remoto de IA configurado.", fr: "Le chat utilise le backend IA distant configuré.", zh: "聊天正在使用已配置的远程 AI 后端。", ar: "تستخدم الدردشة الخلفية البعيدة للذكاء الاصطناعي المُعدّة.", da: "Chatten bruger den konfigurerede eksterne AI-backend.", nb: "Chatten bruker den konfigurerte eksterne AI-backenden.", sv: "Chatten använder den konfigurerade externa AI-backenden.") }
    func sourceOpenAI(_ model: String) -> String {
        "OpenAI · \(model)"
    }
    var sourceOpenAIDetail: String { text(it: "La chat usa direttamente OpenAI.", en: "The chat uses OpenAI directly.", es: "El chat usa OpenAI directamente.", fr: "Le chat utilise directement OpenAI.", zh: "聊天直接使用 OpenAI。", ar: "تستخدم الدردشة OpenAI مباشرة.", da: "Chatten bruger OpenAI direkte.", nb: "Chatten bruker OpenAI direkte.", sv: "Chatten använder OpenAI direkt.") }
    var sourceFoundationModel: String { text(it: "Apple Foundation Model", en: "Apple Foundation Model", es: "Apple Foundation Model", fr: "Apple Foundation Model", zh: "Apple Foundation Model", ar: "Apple Foundation Model", da: "Apple Foundation Model", nb: "Apple Foundation Model", sv: "Apple Foundation Model") }
    var sourceFoundationDetail: String { text(it: "Risposta on-device con Apple Intelligence.", en: "On-device response with Apple Intelligence.", es: "Respuesta en el dispositivo con Apple Intelligence.", fr: "Réponse sur l'appareil avec Apple Intelligence.", zh: "由 Apple Intelligence 在设备端生成回复。", ar: "رد على الجهاز باستخدام Apple Intelligence.", da: "Svar på enheden med Apple Intelligence.", nb: "Svar på enheten med Apple Intelligence.", sv: "Svar på enheten med Apple Intelligence.") }
    var sourceBackendAI: String { text(it: "Backend AI", en: "AI backend", es: "Backend de IA", fr: "Backend IA", zh: "AI 后端", ar: "خلفية الذكاء الاصطناعي", da: "AI-backend", nb: "AI-backend", sv: "AI-backend") }
    var sourceLocalResponseDetail: String { text(it: "Risposta generata dal backend locale su http://127.0.0.1:8787.", en: "Reply generated by the local backend at http://127.0.0.1:8787.", es: "Respuesta generada por el backend local en http://127.0.0.1:8787.", fr: "Réponse générée par le backend local sur http://127.0.0.1:8787.", zh: "回复由本地后端 http://127.0.0.1:8787 生成。", ar: "تم إنشاء الرد بواسطة الخلفية المحلية على http://127.0.0.1:8787.", da: "Svar genereret af den lokale backend på http://127.0.0.1:8787.", nb: "Svar generert av den lokale backenden på http://127.0.0.1:8787.", sv: "Svar genererat av den lokala backendtjänsten på http://127.0.0.1:8787.") }
    var sourceConfiguredResponseDetail: String { text(it: "Risposta generata dal backend AI configurato.", en: "Reply generated by the configured AI backend.", es: "Respuesta generada por el backend de IA configurado.", fr: "Réponse générée par le backend IA configuré.", zh: "回复由已配置的 AI 后端生成。", ar: "تم إنشاء الرد بواسطة خلفية الذكاء الاصطناعي المُعدّة.", da: "Svar genereret af den konfigurerede AI-backend.", nb: "Svar generert av den konfigurerte AI-backenden.", sv: "Svar genererat av den konfigurerade AI-backenden.") }
    func appleIntelligenceUnavailable(_ detail: String) -> String {
        text(it: "Apple Intelligence non disponibile: \(detail).", en: "Apple Intelligence unavailable: \(detail).", es: "Apple Intelligence no disponible: \(detail).", fr: "Apple Intelligence indisponible : \(detail).", zh: "Apple Intelligence 不可用：\(detail)。", ar: "Apple Intelligence غير متاح: \(detail).", da: "Apple Intelligence er ikke tilgængelig: \(detail).", nb: "Apple Intelligence er ikke tilgjengelig: \(detail).", sv: "Apple Intelligence är inte tillgängligt: \(detail).")
    }

    var purchasePremiumActive: String { premiumActive }
    func purchasePremiumMonthly(price: String) -> String {
        text(it: "Attiva Premium · \(price) al mese", en: "Activate Premium · \(price) per month", es: "Activar Premium · \(price) al mes", fr: "Activer Premium · \(price) par mois", zh: "开通 Premium · 每月 \(price)", ar: "فعّل Premium · \(price) شهرياً", da: "Aktivér Premium · \(price) pr. måned", nb: "Aktiver Premium · \(price) per måned", sv: "Aktivera Premium · \(price) per månad")
    }
    var purchaseActivatePremium: String { text(it: "Attiva Premium", en: "Activate Premium", es: "Activar Premium", fr: "Activer Premium", zh: "开通 Premium", ar: "فعّل Premium", da: "Aktivér Premium", nb: "Aktiver Premium", sv: "Aktivera Premium") }
    var premiumActiveAccount: String { text(it: "Premium attivo su questo account. Gli acquisti si ripristinano automaticamente quando disponibili.", en: "Premium is active on this account. Purchases restore automatically when available.", es: "Premium está activo en esta cuenta. Las compras se restauran automáticamente cuando están disponibles.", fr: "Premium est actif sur ce compte. Les achats se restaurent automatiquement quand ils sont disponibles.", zh: "此账户已启用 Premium。可用时购买会自动恢复。", ar: "Premium مفعّل على هذا الحساب. تتم استعادة المشتريات تلقائياً عند توفرها.", da: "Premium er aktiv på denne konto. Køb gendannes automatisk, når de er tilgængelige.", nb: "Premium er aktiv på denne kontoen. Kjøp gjenopprettes automatisk når de er tilgjengelige.", sv: "Premium är aktivt på det här kontot. Köp återställs automatiskt när de är tillgängliga.") }
    var purchaseUsesStoreKit: String { text(it: "L'acquisto usa StoreKit e si sblocca tramite il tuo account App Store.", en: "This purchase uses StoreKit and unlocks through your App Store account.", es: "La compra usa StoreKit y se desbloquea con tu cuenta de App Store.", fr: "L'achat utilise StoreKit et se débloque via ton compte App Store.", zh: "此购买使用 StoreKit，并通过你的 App Store 账户解锁。", ar: "تستخدم عملية الشراء StoreKit ويتم التفعيل عبر حساب App Store الخاص بك.", da: "Købet bruger StoreKit og låses op via din App Store-konto.", nb: "Kjøpet bruker StoreKit og låses opp via App Store-kontoen din.", sv: "Köpet använder StoreKit och låses upp via ditt App Store-konto.") }
    var purchaseLoadingProducts: String { text(it: "Sto caricando le opzioni di acquisto da App Store.", en: "Loading purchase options from the App Store.", es: "Cargando opciones de compra desde App Store.", fr: "Chargement des options d'achat depuis l'App Store.", zh: "正在从 App Store 加载购买选项。", ar: "جارٍ تحميل خيارات الشراء من App Store.", da: "Indlæser købsmuligheder fra App Store.", nb: "Laster inn kjøpsalternativer fra App Store.", sv: "Laddar köpalternativ från App Store.") }
    var refreshShop: String { text(it: "Ricarica lo shop", en: "Reload the shop", es: "Recargar la tienda", fr: "Recharger la boutique", zh: "重新加载商店", ar: "أعد تحميل المتجر", da: "Genindlæs butikken", nb: "Last inn butikken på nytt", sv: "Ladda om butiken") }
    var storeOfferReadyTitle: String { text(it: "Prodotto premium rilevato", en: "Premium product detected", es: "Producto premium detectado", fr: "Produit premium détecté", zh: "已检测到 Premium 产品", ar: "تم اكتشاف منتج Premium", da: "Premium-produkt fundet", nb: "Premium-produkt funnet", sv: "Premiumprodukt hittat") }
    func storeOfferReadyBody(name: String, price: String) -> String {
        text(it: "\(name) disponibile a \(price).", en: "\(name) available for \(price).", es: "\(name) disponible por \(price).", fr: "\(name) disponible à \(price).", zh: "\(name) 可用，价格为 \(price)。", ar: "\(name) متاح بسعر \(price).", da: "\(name) er tilgængeligt til \(price).", nb: "\(name) er tilgjengelig for \(price).", sv: "\(name) är tillgänglig för \(price).")
    }
    var storeOfferMissingTitle: String { text(it: "Il prodotto premium non e ancora arrivato", en: "The premium product hasn't arrived yet", es: "El producto premium aún no ha llegado", fr: "Le produit premium n'est pas encore arrivé", zh: "Premium 产品尚未返回", ar: "لم يصل منتج Premium بعد", da: "Premium-produktet er ikke kommet endnu", nb: "Premium-produktet har ikke kommet ennå", sv: "Premiumprodukten har inte kommit än") }
    var storeOfferMissingBody: String { text(it: "Se stai testando in locale, riapri lo shop con lo schema Peace e la configurazione StoreKit attiva. Se sei in sandbox o produzione, verifica che il prodotto sia pronto su App Store Connect.", en: "If you're testing locally, reopen the shop with the Peace scheme and StoreKit configuration enabled. If you're in sandbox or production, make sure the product is ready in App Store Connect.", es: "Si estás probando en local, vuelve a abrir la tienda con el scheme Peace y la configuración de StoreKit activa. Si estás en sandbox o producción, verifica que el producto esté listo en App Store Connect.", fr: "Si tu testes en local, rouvre la boutique avec le scheme Peace et la configuration StoreKit active. En sandbox ou en production, vérifie que le produit soit prêt dans App Store Connect.", zh: "如果你在本地测试，请使用启用了 StoreKit 配置的 Peace scheme 重新打开商店。如果你在 sandbox 或生产环境，请确认 App Store Connect 中的产品已就绪。", ar: "إذا كنت تختبر محلياً، فأعد فتح المتجر باستخدام مخطط Peace مع تفعيل إعداد StoreKit. وإذا كنت في sandbox أو الإنتاج، فتأكد من أن المنتج جاهز في App Store Connect.", da: "Hvis du tester lokalt, så åbn butikken igen med Peace-scheme og aktiv StoreKit-konfiguration. Hvis du er i sandbox eller produktion, skal du kontrollere, at produktet er klar i App Store Connect.", nb: "Hvis du tester lokalt, åpner du butikken på nytt med Peace-skjemaet og aktiv StoreKit-konfigurasjon. Hvis du er i sandbox eller produksjon, må du kontrollere at produktet er klart i App Store Connect.", sv: "Om du testar lokalt, öppna butiken igen med Peace-schemat och aktiv StoreKit-konfiguration. Om du är i sandbox eller produktion, kontrollera att produkten är klar i App Store Connect.") }
    func shopNotReady(productIDs: String) -> String {
        text(it: "Lo shop non e ancora pronto. In debug usa lo schema Peace con la configurazione locale MindMesh.storekit; per sandbox o produzione serve anche il prodotto App Store Connect con ID \(productIDs).", en: "The shop isn't ready yet. In debug, use the Peace scheme with the local MindMesh.storekit configuration; for sandbox or production you also need the App Store Connect product with ID \(productIDs).", es: "La tienda todavía no está lista. En debug usa el scheme Peace con la configuración local de MindMesh.storekit; para sandbox o producción también necesitas el producto de App Store Connect con ID \(productIDs).", fr: "La boutique n'est pas encore prête. En debug, utilise le scheme Peace avec la configuration locale MindMesh.storekit ; pour sandbox ou production, il faut aussi le produit App Store Connect avec l'ID \(productIDs).", zh: "商店尚未准备好。调试时请使用带有本地 MindMesh.storekit 配置的 Peace scheme；在 sandbox 或生产环境中，还需要 App Store Connect 中 ID 为 \(productIDs) 的产品。", ar: "المتجر غير جاهز بعد. في وضع التطوير استخدم مخطط Peace مع إعداد MindMesh.storekit المحلي؛ ولبيئة sandbox أو الإنتاج تحتاج أيضاً إلى منتج App Store Connect بالمعرّف \(productIDs).", da: "Butikken er ikke klar endnu. I debug skal du bruge Peace-scheme med den lokale MindMesh.storekit-konfiguration; til sandbox eller produktion skal App Store Connect-produktet med ID \(productIDs) også være oprettet.", nb: "Butikken er ikke klar ennå. I debug må du bruke Peace-skjemaet med lokal MindMesh.storekit-konfigurasjon; for sandbox eller produksjon trenger du også App Store Connect-produktet med ID \(productIDs).", sv: "Butiken är inte redo ännu. I debug ska du använda Peace-schemat med den lokala MindMesh.storekit-konfigurationen; för sandbox eller produktion behövs också App Store Connect-produkten med ID \(productIDs).")
    }
    func noPremiumProductFound(productIDs: String) -> String {
        text(it: "Nessun prodotto premium trovato. Verifica la configurazione locale MindMesh.storekit oppure il prodotto App Store Connect con ID \(productIDs).", en: "No premium product found. Check the local MindMesh.storekit configuration or the App Store Connect product with ID \(productIDs).", es: "No se encontró ningún producto premium. Revisa la configuración local de MindMesh.storekit o el producto de App Store Connect con ID \(productIDs).", fr: "Aucun produit premium trouvé. Vérifie la configuration locale MindMesh.storekit ou le produit App Store Connect avec l'ID \(productIDs).", zh: "未找到 Premium 产品。请检查本地 MindMesh.storekit 配置或 App Store Connect 中 ID 为 \(productIDs) 的产品。", ar: "لم يتم العثور على منتج Premium. تحقّق من إعداد MindMesh.storekit المحلي أو من منتج App Store Connect بالمعرّف \(productIDs).", da: "Intet premium-produkt fundet. Tjek den lokale MindMesh.storekit-konfiguration eller App Store Connect-produktet med ID \(productIDs).", nb: "Fant ingen premium-produkt. Sjekk lokal MindMesh.storekit-konfigurasjon eller App Store Connect-produktet med ID \(productIDs).", sv: "Ingen premiumprodukt hittades. Kontrollera den lokala MindMesh.storekit-konfigurationen eller App Store Connect-produkten med ID \(productIDs).")
    }
    var cannotLoadShop: String { text(it: "Non riesco a caricare lo shop in questo momento.", en: "I can't load the shop right now.", es: "No puedo cargar la tienda en este momento.", fr: "Je ne peux pas charger la boutique pour le moment.", zh: "目前无法加载商店。", ar: "لا يمكنني تحميل المتجر الآن.", da: "Jeg kan ikke indlæse butikken lige nu.", nb: "Jeg kan ikke laste inn butikken akkurat nå.", sv: "Jag kan inte ladda butiken just nu.") }
    var premiumProductUnavailable: String { text(it: "Il prodotto premium non e disponibile. Controlla che lo schema Peace usi MindMesh.storekit oppure che il prodotto App Store Connect sia pronto.", en: "The premium product isn't available. Check that the Peace scheme uses MindMesh.storekit or that the App Store Connect product is ready.", es: "El producto premium no está disponible. Comprueba que el scheme Peace use MindMesh.storekit o que el producto de App Store Connect esté listo.", fr: "Le produit premium n'est pas disponible. Vérifie que le scheme Peace utilise MindMesh.storekit ou que le produit App Store Connect soit prêt.", zh: "Premium 产品不可用。请检查 Peace scheme 是否使用了 MindMesh.storekit，或确认 App Store Connect 产品已准备好。", ar: "منتج Premium غير متاح. تحقق من أن مخطط Peace يستخدم MindMesh.storekit أو أن منتج App Store Connect جاهز.", da: "Premium-produktet er ikke tilgængeligt. Tjek at Peace-scheme bruger MindMesh.storekit, eller at App Store Connect-produktet er klar.", nb: "Premium-produktet er ikke tilgjengelig. Sjekk at Peace-skjemaet bruker MindMesh.storekit, eller at App Store Connect-produktet er klart.", sv: "Premiumprodukten är inte tillgänglig. Kontrollera att Peace-schemat använder MindMesh.storekit eller att App Store Connect-produkten är klar.") }
    var premiumActivated: String { text(it: "Premium attivato correttamente.", en: "Premium activated successfully.", es: "Premium activado correctamente.", fr: "Premium activé avec succès.", zh: "Premium 已成功激活。", ar: "تم تفعيل Premium بنجاح.", da: "Premium blev aktiveret.", nb: "Premium ble aktivert.", sv: "Premium aktiverades.") }
    var purchasePending: String { text(it: "L'acquisto e in attesa di conferma.", en: "The purchase is pending confirmation.", es: "La compra está pendiente de confirmación.", fr: "L'achat est en attente de confirmation.", zh: "购买正在等待确认。", ar: "عملية الشراء بانتظار التأكيد.", da: "Købet afventer bekræftelse.", nb: "Kjøpet venter på bekreftelse.", sv: "Köpet väntar på bekräftelse.") }
    var purchaseUnknownState: String { text(it: "Stato acquisto non riconosciuto.", en: "Unrecognized purchase state.", es: "Estado de compra no reconocido.", fr: "État d'achat non reconnu.", zh: "无法识别的购买状态。", ar: "حالة شراء غير معروفة.", da: "Ukendt købstatus.", nb: "Ukjent kjøpstilstand.", sv: "Okänt köpstatus.") }
    var purchaseFailed: String { text(it: "L'acquisto non e andato a buon fine. Se stai testando in locale, avvia l'app dallo schema Peace con la configurazione StoreKit inclusa.", en: "The purchase didn't complete successfully. If you're testing locally, launch the app from the Peace scheme with the included StoreKit configuration.", es: "La compra no se completó correctamente. Si estás probando en local, inicia la app desde el scheme Peace con la configuración StoreKit incluida.", fr: "L'achat n'a pas abouti. Si tu testes en local, lance l'app depuis le scheme Peace avec la configuration StoreKit incluse.", zh: "购买未成功完成。如果你在本地测试，请使用包含 StoreKit 配置的 Peace scheme 启动应用。", ar: "لم تكتمل عملية الشراء بنجاح. إذا كنت تختبر محلياً، فشغّل التطبيق من مخطط Peace مع إعداد StoreKit المضمّن.", da: "Købet blev ikke gennemført. Hvis du tester lokalt, skal du starte appen fra Peace-scheme med den inkluderede StoreKit-konfiguration.", nb: "Kjøpet ble ikke fullført. Hvis du tester lokalt, start appen fra Peace-skjemaet med den inkluderte StoreKit-konfigurasjonen.", sv: "Köpet slutfördes inte. Om du testar lokalt, starta appen från Peace-schemat med den inkluderade StoreKit-konfigurationen.") }
    var purchasesRestored: String { text(it: "Acquisti ripristinati.", en: "Purchases restored.", es: "Compras restauradas.", fr: "Achats restaurés.", zh: "购买已恢复。", ar: "تمت استعادة المشتريات.", da: "Køb gendannet.", nb: "Kjøp gjenopprettet.", sv: "Köp återställda.") }
    var noPremiumPurchaseFound: String { text(it: "Nessun acquisto Premium trovato per questo account.", en: "No Premium purchase found for this account.", es: "No se encontró ninguna compra Premium para esta cuenta.", fr: "Aucun achat Premium trouvé pour ce compte.", zh: "此账户未找到 Premium 购买记录。", ar: "لم يتم العثور على أي عملية شراء Premium لهذا الحساب.", da: "Ingen Premium-køb fundet for denne konto.", nb: "Fant ingen Premium-kjøp for denne kontoen.", sv: "Inget Premium-köp hittades för det här kontot.") }
    var restoreFailed: String { text(it: "Non riesco a ripristinare gli acquisti in questo momento.", en: "I can't restore purchases right now.", es: "No puedo restaurar las compras en este momento.", fr: "Je ne peux pas restaurer les achats pour le moment.", zh: "目前无法恢复购买。", ar: "لا يمكنني استعادة المشتريات الآن.", da: "Jeg kan ikke gendanne køb lige nu.", nb: "Jeg kan ikke gjenopprette kjøp akkurat nå.", sv: "Jag kan inte återställa köp just nu.") }
    var purchaseUpdateUnverified: String { text(it: "Aggiornamento acquisto non verificato.", en: "Purchase update not verified.", es: "Actualización de compra no verificada.", fr: "Mise à jour d'achat non vérifiée.", zh: "购买更新未验证。", ar: "تحديث الشراء غير موثّق.", da: "Købsopdatering ikke verificeret.", nb: "Kjøpsoppdatering ikke verifisert.", sv: "Köpuppdateringen verifierades inte.") }
    var debugPremiumUnlocked: String { text(it: "Premium attivato in locale per il test.", en: "Premium unlocked locally for testing.", es: "Premium activado localmente para pruebas.", fr: "Premium activé localement pour les tests.", zh: "Premium 已在本地测试环境中解锁。", ar: "تم تفعيل Premium محلياً للاختبار.", da: "Premium aktiveret lokalt til test.", nb: "Premium aktivert lokalt for testing.", sv: "Premium aktiverat lokalt för test.") }
    var debugPremiumStatus: String { text(it: "StoreKit locale non disponibile: in debug puoi comunque sbloccare Premium per testare lo shop e tutte le funzioni premium.", en: "Local StoreKit isn't available: in debug you can still unlock Premium to test the paywall and premium features.", es: "StoreKit local no está disponible: en debug aún puedes desbloquear Premium para probar la tienda y las funciones premium.", fr: "StoreKit local n'est pas disponible : en debug, tu peux quand même débloquer Premium pour tester la boutique et les fonctions premium.", zh: "本地 StoreKit 当前不可用：在调试环境中你仍可解锁 Premium 以测试付费墙和高级功能。", ar: "StoreKit المحلي غير متاح حالياً: في وضع التصحيح لا يزال بإمكانك فتح Premium لاختبار المتجر والميزات المدفوعة.", da: "Lokal StoreKit er ikke tilgængelig: i debug kan du stadig låse Premium op for at teste shop og premiumfunktioner.", nb: "Lokal StoreKit er ikke tilgjengelig: i debug kan du fortsatt låse opp Premium for å teste paywall og premiumfunksjoner.", sv: "Lokal StoreKit är inte tillgänglig: i debug kan du ändå låsa upp Premium för att testa betalväggen och premiumfunktionerna.") }
}
